[2025-07-22T05:58:53.228+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-22T05:58:53.255+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.fetch_forecast manual__2025-07-22T05:58:49.417367+00:00 [queued]>
[2025-07-22T05:58:53.264+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.fetch_forecast manual__2025-07-22T05:58:49.417367+00:00 [queued]>
[2025-07-22T05:58:53.264+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-22T05:58:53.277+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_forecast> on 2025-07-22 05:58:49.417367+00:00
[2025-07-22T05:58:53.285+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'fetch_forecast', 'manual__2025-07-22T05:58:49.417367+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpoqli8rac']
[2025-07-22T05:58:53.288+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=184) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-22T05:58:53.288+0000] {standard_task_runner.py:91} INFO - Job 113: Subtask fetch_forecast
[2025-07-22T05:58:53.289+0000] {standard_task_runner.py:63} INFO - Started process 186 to run task
[2025-07-22T05:58:53.331+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.fetch_forecast manual__2025-07-22T05:58:49.417367+00:00 [running]> on host c3976269ce0f
[2025-07-22T05:58:53.401+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='fetch_forecast' AIRFLOW_CTX_EXECUTION_DATE='2025-07-22T05:58:49.417367+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-22T05:58:49.417367+00:00'
[2025-07-22T05:58:53.403+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-22T05:58:53.413+0000] {weather_dag.py:53} INFO - Bắt đầu gọi API thời tiết...
[2025-07-22T05:59:03.468+0000] {weather_dag.py:98} INFO - Các cột có giá trị None: name                           0
forecast_time                  0
temperature                    0
temperatureApparent            0
dewPoint                       0
humidity                       0
windSpeed                      0
windDirection                  0
windGust                       0
pressureSurfaceLevel           0
cloudCover                     0
precipitationProbability       0
uvIndex                      160
ezHeatStressIndex           1200
dtype: int64
[2025-07-22T05:59:03.471+0000] {weather_dag.py:102} WARNING - Cột name vẫn chứa chuỗi 'nan'!
[2025-07-22T05:59:03.497+0000] {weather_dag.py:102} WARNING - Cột uvIndex vẫn chứa chuỗi 'nan'!
[2025-07-22T05:59:03.538+0000] {weather_dag.py:114} INFO - name                        object
forecast_time               object
temperature                 object
temperatureApparent         object
dewPoint                    object
humidity                     int64
windSpeed                   object
windDirection                int64
windGust                    object
pressureSurfaceLevel        object
cloudCover                   int64
precipitationProbability     int64
uvIndex                     object
ezHeatStressIndex           object
dtype: object
[2025-07-22T05:59:04.065+0000] {weather_dag.py:137} INFO - Đã insert 1200 dòng dữ liệu thời tiết
[2025-07-22T05:59:04.069+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-22T05:59:04.070+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-22T05:59:04.081+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=fetch_forecast, run_id=manual__2025-07-22T05:58:49.417367+00:00, execution_date=20250722T055849, start_date=20250722T055853, end_date=20250722T055904
[2025-07-22T05:59:04.114+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-22T05:59:04.130+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-22T05:59:04.132+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
