[2025-07-22T04:07:28.522+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-22T04:07:28.551+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.fetch_forecast manual__2025-07-22T04:07:25.447697+00:00 [queued]>
[2025-07-22T04:07:28.560+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.fetch_forecast manual__2025-07-22T04:07:25.447697+00:00 [queued]>
[2025-07-22T04:07:28.561+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-22T04:07:28.572+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_forecast> on 2025-07-22 04:07:25.447697+00:00
[2025-07-22T04:07:28.581+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=181) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-22T04:07:28.579+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'fetch_forecast', 'manual__2025-07-22T04:07:25.447697+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpw2biy1s4']
[2025-07-22T04:07:28.582+0000] {standard_task_runner.py:63} INFO - Started process 185 to run task
[2025-07-22T04:07:28.582+0000] {standard_task_runner.py:91} INFO - Job 97: Subtask fetch_forecast
[2025-07-22T04:07:28.627+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.fetch_forecast manual__2025-07-22T04:07:25.447697+00:00 [running]> on host 6a52d07e004b
[2025-07-22T04:07:28.700+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='fetch_forecast' AIRFLOW_CTX_EXECUTION_DATE='2025-07-22T04:07:25.447697+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-22T04:07:25.447697+00:00'
[2025-07-22T04:07:28.701+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-22T04:07:28.713+0000] {weather_dag.py:53} INFO - Bắt đầu gọi API thời tiết...
[2025-07-22T04:07:38.950+0000] {weather_dag.py:98} INFO - Các cột có giá trị None: name                           0
forecast_time                  0
temperature                    0
temperatureApparent            0
dewPoint                       0
humidity                       0
windSpeed                      0
windDirection                  0
windGust                       0
pressureSurfaceLevel           0
cloudCover                     0
precipitationProbability       0
uvIndex                      150
ezHeatStressIndex           1200
dtype: int64
[2025-07-22T04:07:38.955+0000] {weather_dag.py:102} WARNING - Cột name vẫn chứa chuỗi 'nan'!
[2025-07-22T04:07:38.969+0000] {weather_dag.py:102} WARNING - Cột uvIndex vẫn chứa chuỗi 'nan'!
[2025-07-22T04:07:39.006+0000] {weather_dag.py:114} INFO - name                        object
forecast_time               object
temperature                 object
temperatureApparent         object
dewPoint                    object
humidity                     int64
windSpeed                   object
windDirection                int64
windGust                    object
pressureSurfaceLevel        object
cloudCover                   int64
precipitationProbability     int64
uvIndex                     object
ezHeatStressIndex           object
dtype: object
[2025-07-22T04:07:39.370+0000] {weather_dag.py:137} INFO - Đã insert 1200 dòng dữ liệu thời tiết
[2025-07-22T04:07:39.373+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-22T04:07:39.374+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-22T04:07:39.383+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=fetch_forecast, run_id=manual__2025-07-22T04:07:25.447697+00:00, execution_date=20250722T040725, start_date=20250722T040728, end_date=20250722T040739
[2025-07-22T04:07:39.439+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-22T04:07:39.455+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-22T04:07:39.457+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
