[2025-07-21T03:14:45.892+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-21T03:14:45.923+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_weather_foreacst_dag.fetch_forecast manual__2025-07-21T03:14:43.851132+00:00 [queued]>
[2025-07-21T03:14:45.932+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_weather_foreacst_dag.fetch_forecast manual__2025-07-21T03:14:43.851132+00:00 [queued]>
[2025-07-21T03:14:45.933+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-21T03:14:45.945+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_forecast> on 2025-07-21 03:14:43.851132+00:00
[2025-07-21T03:14:45.953+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_weather_foreacst_dag', 'fetch_forecast', 'manual__2025-07-21T03:14:43.851132+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmplabncs3s']
[2025-07-21T03:14:45.956+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=190) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-21T03:14:45.956+0000] {standard_task_runner.py:91} INFO - Job 68: Subtask fetch_forecast
[2025-07-21T03:14:45.957+0000] {standard_task_runner.py:63} INFO - Started process 192 to run task
[2025-07-21T03:14:46.002+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_weather_foreacst_dag.fetch_forecast manual__2025-07-21T03:14:43.851132+00:00 [running]> on host 2d54aaf25bca
[2025-07-21T03:14:46.081+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_weather_foreacst_dag' AIRFLOW_CTX_TASK_ID='fetch_forecast' AIRFLOW_CTX_EXECUTION_DATE='2025-07-21T03:14:43.851132+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-21T03:14:43.851132+00:00'
[2025-07-21T03:14:46.083+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-21T03:14:46.093+0000] {weather_dag.py:49} INFO - Bắt đầu gọi API thời tiết...
[2025-07-21T03:14:51.917+0000] {weather_dag.py:81} WARNING - Rate limit cho Can Tho. Bỏ qua
[2025-07-21T03:14:52.382+0000] {weather_dag.py:81} WARNING - Rate limit cho Bien Hoa. Bỏ qua
[2025-07-21T03:14:52.830+0000] {weather_dag.py:81} WARNING - Rate limit cho Quang Ninh. Bỏ qua
[2025-07-21T03:14:53.306+0000] {weather_dag.py:81} WARNING - Rate limit cho Nghe An. Bỏ qua
[2025-07-21T03:14:53.759+0000] {weather_dag.py:81} WARNING - Rate limit cho Ninh Binh. Bỏ qua
[2025-07-21T03:14:53.768+0000] {weather_dag.py:94} INFO - Các cột có giá trị None: name                          0
forecast_time                 0
temperature                   0
temperatureApparent           0
dewPoint                      0
humidity                      0
windSpeed                     0
windDirection                 0
windGust                      0
pressureSurfaceLevel          0
cloudCover                    0
precipitationProbability      0
uvIndex                      70
ezHeatStressIndex           600
dtype: int64
[2025-07-21T03:14:53.772+0000] {weather_dag.py:98} WARNING - Cột name vẫn chứa chuỗi 'nan'!
[2025-07-21T03:14:53.780+0000] {weather_dag.py:98} WARNING - Cột uvIndex vẫn chứa chuỗi 'nan'!
[2025-07-21T03:14:53.843+0000] {weather_dag.py:127} ERROR - Lỗi khi ghi dữ liệu vào DB 1054 (42S22): Unknown column 'nan' in 'field list'
[2025-07-21T03:14:53.845+0000] {weather_dag.py:131} INFO - Đã insert 600 dòng dữ liệu thời tiết
[2025-07-21T03:14:53.847+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-21T03:14:53.848+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-21T03:14:53.856+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=fetch_weather_foreacst_dag, task_id=fetch_forecast, run_id=manual__2025-07-21T03:14:43.851132+00:00, execution_date=20250721T031443, start_date=20250721T031445, end_date=20250721T031453
[2025-07-21T03:14:53.884+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-21T03:14:53.896+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-21T03:14:53.898+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
